name: task-manager
services:
  frontend:
    container_name: tm-frontend-angular-nginx
    build: ./frontend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-node
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      - tmnetwork
  
  backend-node:
    container_name: tm-backend-node
    build: ./backend-node
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - tmnetwork

  backend-csharp:
    container_name: tm-backend-csharp
    build: ./backend-csharp
    depends_on:
      - rabbitmq
      - redis
    networks:
      - tmnetwork

  postgres:
    container_name: tm-postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tmnetwork

  pgadmin:
    container_name: tm-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - tmnetwork

  rabbitmq:
    container_name: tm-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    networks:
      - tmnetwork

  redis:
    container_name: tm-redis
    image: redis:latest
    ports:
    - 6379:6379
    networks:
      - tmnetwork

volumes:
  postgres:

networks:
  tmnetwork:
    driver: bridge